name: Push Docker Image

on:
  workflow_call:
    inputs:
      version:
        description: The version of Red5 Server to be pushed
        type: string
        required: true
    secrets:
      dockerhub-password:
        description: Docker Hub password
        required: true
      dockerhub-username:
        description: Docker Hub username
        required: true
      dockerhub-repository:
        description: Docker Hub repository (e.g., username/repository)
        required: true

jobs:
  substring-version:
    if: github.repository == 'Juansecu/red5-server'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.substring.outputs.substring }}
    steps:
      - name: Substring version
        id: substring
        uses: bhowell2/github-substring-action@1.0.2
        with:
          value: ${{ inputs.version }}
          index_of_str: v

  retrieve-version-parts:
    if: github.repository == 'Juansecu/red5-server'
    runs-on: ubuntu-latest
    needs: substring-version
    outputs:
      major-version: ${{ steps.split.outputs._0 }}
      minor-version: ${{ steps.split.outputs._1 }}
      patch-version: ${{ steps.split.outputs._2 }}
    steps:
      - name: Retrieve version parts
        id: split
        uses: winterjung/split@v2
        with:
          msg: ${{ needs.substring-version.outputs.version }}
          separator: .

  push-docker-image:
    if: github.repository == 'Juansecu/red5-server'
    runs-on: ubuntu-latest
    needs: retrieve-version-parts
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'Juansecu/Red5-Docker'
          path: docker-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          password: ${{ secrets.dockerhub-password }}
          username: ${{ secrets.dockerhub-username }}
      - name: Debug repository contents
        run: |
          pwd
          ls -la docker-repo
          git ls-files -s docker-repo/Dockerfile
          cat docker-repo/Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        env:
          RED5_VERSION: ${{ needs.retrieve-version-parts.outputs.major-version }}.${{needs.retrieve-version-parts.outputs.minor-version}}.${{ needs.retrieve-version-parts.outputs.patch-version }}
        with:
          build-args: |
            RED5_VERSION=${{ env.RED5_VERSION }}
          context: .
          file: ./docker-repo/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.dockerhub-repository }}:${{ env.RED5_VERSION }}
            ${{ secrets.dockerhub-repository }}:${{ needs.retrieve-version-parts.outputs.major-version }}
            ${{ secrets.dockerhub-repository }}:${{ needs.retrieve-version-parts.outputs.major-version }}.${{ needs.retrieve-version-parts.outputs.minor-version }}
            ${{ secrets.dockerhub-repository }}:latest
